from pyglet.gl import *

CUBE = 1

YPOS = 2
YNEG = 3
XPOS = 4
XNEG = 5
ZPOS = 6
ZNEG = 7

UNLITCUBE = 8

o = 1
O = 1.01

def draw_cube():
	glColor3f(0.75,0.75,0.75)
	glNormal3f(0,0,-1)
	glTexCoord2f( 0, 0)
	glVertex3f( -o, -o, -o)
	glTexCoord2f( 1, 0)
	glVertex3f(  o, -o, -o)
	glTexCoord2f( 1, 1)
	glVertex3f(  o,  o, -o)
	glTexCoord2f( 0, 1)
	glVertex3f( -o,  o, -o)
	glColor3f(0.8,0.8,0.8)
	glNormal3f(0,0,1)
	glTexCoord2f( 0, 0)
	glVertex3f( -o, -o,  o)
	glTexCoord2f( 1, 0)
	glVertex3f(  o, -o,  o)
	glTexCoord2f( 1, 1)
	glVertex3f(  o,  o,  o)
	glTexCoord2f( 0, 1)
	glVertex3f( -o,  o,  o)
	glColor3f(0.5,0.5,0.5)
	glNormal3f(0,-1,0) 
	glTexCoord2f( 0, 0)
	glVertex3f( -o, -o, -o)
	glTexCoord2f( 1, 0)
	glVertex3f(  o, -o, -o)
	glTexCoord2f( 1, 1)
	glVertex3f(  o, -o,  o)
	glTexCoord2f( 0, 1)
	glVertex3f( -o, -o,  o)
	glColor3f(1.0,1.0,1.0)
	glNormal3f(0,1,0) 
	glTexCoord2f( 0, 0)
	glVertex3f( -o,  o, -o)
	glTexCoord2f( 1, 0)
	glVertex3f(  o,  o, -o)
	glTexCoord2f( 1, 1)
	glVertex3f(  o,  o,  o)
	glTexCoord2f( 0, 1)
	glVertex3f( -o,  o,  o)
	glColor3f(0.85,0.85,0.85)
	glNormal3f(-1,0,0)
	glTexCoord2f( 0, 0)
	glVertex3f( -o, -o, -o)
	glTexCoord2f( 1, 0)
	glVertex3f( -o,  o, -o)
	glTexCoord2f( 1, 1)
	glVertex3f( -o,  o,  o)
	glTexCoord2f( 0, 1)
	glVertex3f( -o, -o,  o)                      
	glColor3f(0.9,0.9,0.9)
	glNormal3f(1,0,0)
	glTexCoord2f( 0, 0)
	glVertex3f(  o, -o, -o)
	glTexCoord2f( 1, 0)
	glVertex3f(  o,  o, -o)
	glTexCoord2f( 1, 1)
	glVertex3f(  o,  o,  o)
	glTexCoord2f( 0, 1)
	glVertex3f(  o, -o,  o)

def draw_face(face, andColour = True, N=o):
	if face == ZNEG:
		if andColour: glColor3f(0.75,0.75,0.75)
		glNormal3f(0,0,-1)
		glTexCoord2f( 0, 0)
		glVertex3f( -o, -o, -N)
		glTexCoord2f( 1, 0)
		glVertex3f(  o, -o, -N)
		glTexCoord2f( 1, 1)
		glVertex3f(  o,  o, -N)
		glTexCoord2f( 0, 1)
		glVertex3f( -o,  o, -N)
	if face == ZPOS:
		if andColour: glColor3f(0.8,0.8,0.8)
		glNormal3f(0,0,1)
		glTexCoord2f( 0, 0)
		glVertex3f( -o, -o,  N)
		glTexCoord2f( 1, 0)
		glVertex3f(  o, -o,  N)
		glTexCoord2f( 1, 1)
		glVertex3f(  o,  o,  N)
		glTexCoord2f( 0, 1)
		glVertex3f( -o,  o,  N)
	if face == YNEG:
		if andColour: glColor3f(0.5,0.5,0.5)
		glNormal3f(0,-1,0) 
		glTexCoord2f( 0, 0)
		glVertex3f( -o, -N, -o)
		glTexCoord2f( 1, 0)
		glVertex3f(  o, -N, -o)
		glTexCoord2f( 1, 1)
		glVertex3f(  o, -N,  o)
		glTexCoord2f( 0, 1)
		glVertex3f( -o, -N,  o)
	if face == YPOS:
		if andColour: glColor3f(1.0,1.0,1.0)
		glNormal3f(0,1,0) 
		glTexCoord2f( 0, 0)
		glVertex3f( -o,  N, -o)
		glTexCoord2f( 1, 0)
		glVertex3f(  o,  N, -o)
		glTexCoord2f( 1, 1)
		glVertex3f(  o,  N,  o)
		glTexCoord2f( 0, 1)
		glVertex3f( -o,  N,  o)
	if face == XNEG:
		if andColour: glColor3f(0.85,0.85,0.85)
		glNormal3f(-1,0,0)
		glTexCoord2f( 1, 0)
		glVertex3f( -N, -o, -o)
		glTexCoord2f( 1, 1)
		glVertex3f( -N,  o, -o)
		glTexCoord2f( 0, 1)
		glVertex3f( -N,  o,  o)
		glTexCoord2f( 0, 0)
		glVertex3f( -N, -o,  o)                      
	if face == XPOS:
		if andColour: glColor3f(0.9,0.9,0.9)
		glNormal3f(1,0,0)
		glTexCoord2f( 1, 0)
		glVertex3f(  N, -o, -o)
		glTexCoord2f( 1, 1)
		glVertex3f(  N,  o, -o)
		glTexCoord2f( 0, 1)
		glVertex3f(  N,  o,  o)
		glTexCoord2f( 0, 0)
		glVertex3f(  N, -o,  o)

glNewList(CUBE,GL_COMPILE)
glBegin(GL_QUADS)
glColor3f(0.75,0.75,0.75)
glNormal3f(0,0,-1)
glTexCoord2f( 0, 0)
glVertex3f( -o, -o, -o)
glTexCoord2f( 1, 0)
glVertex3f(  o, -o, -o)
glTexCoord2f( 1, 1)
glVertex3f(  o,  o, -o)
glTexCoord2f( 0, 1)
glVertex3f( -o,  o, -o)
glColor3f(0.8,0.8,0.8)
glNormal3f(0,0,1)
glTexCoord2f( 0, 0)
glVertex3f( -o, -o,  o)
glTexCoord2f( 1, 0)
glVertex3f(  o, -o,  o)
glTexCoord2f( 1, 1)
glVertex3f(  o,  o,  o)
glTexCoord2f( 0, 1)
glVertex3f( -o,  o,  o)
glColor3f(0.5,0.5,0.5)
glNormal3f(0,-1,0) 
glTexCoord2f( 0, 0)
glVertex3f( -o, -o, -o)
glTexCoord2f( 1, 0)
glVertex3f(  o, -o, -o)
glTexCoord2f( 1, 1)
glVertex3f(  o, -o,  o)
glTexCoord2f( 0, 1)
glVertex3f( -o, -o,  o)
glColor3f(1.0,1.0,1.0)
glNormal3f(0,1,0) 
glTexCoord2f( 0, 0)
glVertex3f( -o,  o, -o)
glTexCoord2f( 1, 0)
glVertex3f(  o,  o, -o)
glTexCoord2f( 1, 1)
glVertex3f(  o,  o,  o)
glTexCoord2f( 0, 1)
glVertex3f( -o,  o,  o)
glColor3f(0.85,0.85,0.85)
glNormal3f(-1,0,0)
glTexCoord2f( 0, 0)
glVertex3f( -o, -o, -o)
glTexCoord2f( 1, 0)
glVertex3f( -o,  o, -o)
glTexCoord2f( 1, 1)
glVertex3f( -o,  o,  o)
glTexCoord2f( 0, 1)
glVertex3f( -o, -o,  o)                      
glColor3f(0.9,0.9,0.9)
glNormal3f(1,0,0)
glTexCoord2f( 0, 0)
glVertex3f(  o, -o, -o)
glTexCoord2f( 1, 0)
glVertex3f(  o,  o, -o)
glTexCoord2f( 1, 1)
glVertex3f(  o,  o,  o)
glTexCoord2f( 0, 1)
glVertex3f(  o, -o,  o)
glEnd()
glEndList()

glNewList(UNLITCUBE,GL_COMPILE)
glBegin(GL_QUADS)
glNormal3f(0,0,-1)
glTexCoord2f( 0, 0)
glVertex3f( -o, -o, -o)
glTexCoord2f( 1, 0)
glVertex3f(  o, -o, -o)
glTexCoord2f( 1, 1)
glVertex3f(  o,  o, -o)
glTexCoord2f( 0, 1)
glVertex3f( -o,  o, -o)
glNormal3f(0,0,1)
glTexCoord2f( 0, 0)
glVertex3f( -o, -o,  o)
glTexCoord2f( 1, 0)
glVertex3f(  o, -o,  o)
glTexCoord2f( 1, 1)
glVertex3f(  o,  o,  o)
glTexCoord2f( 0, 1)
glVertex3f( -o,  o,  o)
glNormal3f(0,-1,0) 
glTexCoord2f( 0, 0)
glVertex3f( -o, -o, -o)
glTexCoord2f( 1, 0)
glVertex3f(  o, -o, -o)
glTexCoord2f( 1, 1)
glVertex3f(  o, -o,  o)
glTexCoord2f( 0, 1)
glVertex3f( -o, -o,  o)
glNormal3f(0,1,0) 
glTexCoord2f( 0, 0)
glVertex3f( -o,  o, -o)
glTexCoord2f( 1, 0)
glVertex3f(  o,  o, -o)
glTexCoord2f( 1, 1)
glVertex3f(  o,  o,  o)
glTexCoord2f( 0, 1)
glVertex3f( -o,  o,  o)
glNormal3f(-1,0,0)
glTexCoord2f( 0, 0)
glVertex3f( -o, -o, -o)
glTexCoord2f( 1, 0)
glVertex3f( -o,  o, -o)
glTexCoord2f( 1, 1)
glVertex3f( -o,  o,  o)
glTexCoord2f( 0, 1)
glVertex3f( -o, -o,  o)                      
glNormal3f(1,0,0)
glTexCoord2f( 0, 0)
glVertex3f(  o, -o, -o)
glTexCoord2f( 1, 0)
glVertex3f(  o,  o, -o)
glTexCoord2f( 1, 1)
glVertex3f(  o,  o,  o)
glTexCoord2f( 0, 1)
glVertex3f(  o, -o,  o)
glEnd()
glEndList()

def draw_XNEG():
	glBegin(GL_QUADS)
	draw_face(XNEG,False,O)
	glEnd()
def draw_XPOS():
	glBegin(GL_QUADS)
	draw_face(XPOS,False,O)
	glEnd()
def draw_YNEG():
	glBegin(GL_QUADS)
	draw_face(YNEG,False,O)
	glEnd()
def draw_YPOS():
	glBegin(GL_QUADS)
	draw_face(YPOS,False,O)
	glEnd()
def draw_ZNEG():
	glBegin(GL_QUADS)
	draw_face(ZNEG,False,O)
	glEnd()
def draw_ZPOS():
	glBegin(GL_QUADS)
	draw_face(ZPOS,False,O)
	glEnd()

def filloutPrims( state ):
	state.CUBE = CUBE
	state.UNLITCUBE = UNLITCUBE
	state.YPOS = YPOS
	state.YNEG = YNEG
	state.XPOS = XPOS
	state.XNEG = XNEG
	state.ZPOS = ZPOS
	state.ZNEG = ZNEG
	state.draw_face = draw_face
	state.draw_cube = draw_cube
	state.draw_XNEG = draw_ZNEG
	state.draw_XPOS = draw_ZPOS
	state.draw_YNEG = draw_ZNEG
	state.draw_YPOS = draw_ZPOS
	state.draw_ZNEG = draw_ZNEG
	state.draw_ZPOS = draw_ZPOS

